services:
      pollination-frontend:
        restart: on-failure

        labels:
          # make traefik use this sub-domain in entrypoing "http-ep" (as defined in docker-compose.yml)
          # note: router name is arbitrary but must be unique among containers
          - traefik.http.routers.pollination-frontend-insecure.entrypoints=http-ep
          - traefik.http.routers.pollination-frontend-insecure.rule=Host(`pollination.localhost`) && !PathPrefix(`/api`)
